# 배열 만들기

In [18]:
import numpy as np, cv2

a = np.array([[1,2,3,4],[5,6,7,8]]) #2행 4열 [] 하나는 행을 의미
b = np.array([[1],[2],[3],[4]]) #4행 1열

c = a.T #transpose, 4행 2열


array([[208, 198, 227],
       [ 53,  99, 108],
       [ 93, 110, 245]])

In [ ]:
a = np.zeros((2,3), np.uint8)
b = np.full((2,3), 255, np.uint8)
a.fill(255)

In [ ]:
img = cv2.imread('images/read_color.jpg')
a = np.zeros_like(img)

In [20]:
a = np.arange(5)
b = np.arange(0,6,1)

array([0, 1, 2, 3, 4])

In [21]:
a = np.random.randint(0,256,(3,3))

array([[ 66, 208, 158],
       [249, 242, 245],
       [ 38, 129, 209]])

In [33]:
a = np.arange(5)
b = a.astype(np.float64) #이 방법을 주로 씀
c = np.uint8(a)

array([0, 1, 2, 3, 4], dtype=uint8)

# 차원 변경

In [39]:
a = np.arange(6).reshape(2, 3)
b = np.arange(100).reshape(-1, 5)

In [45]:
a = np.zeros((2,3), np.uint8)
b = np.ravel(a)
c = a.flatten()

array([0, 0, 0, 0, 0, 0], dtype=uint8)

In [54]:
a = np.arange(5)
a + 5

b = np.arange(50).reshape(-1,5)
b ** 2
b > 10

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# 브로드캐스팅 연산

In [56]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(12).reshape(3,4)    #(3,4) --> (1,3,4) --> (2,3,4)

print(a)
print(b)

a+b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [59]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(3).reshape(3,1)    #(3,1) --> (1,3,1) --> (2,3,4), 1이 다른 shape과 일치하도록 늘어난다.
print(a)
print(b)
a + b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[0]
 [1]
 [2]]


array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25]]])

In [60]:
a = np.arange(6).reshape(2,3,1)
b = np.arange(6).reshape(2,3)    #(2,3) --> (1,2,3) --> (2,2,3), 차원의 크기가 일치하지 않음
#a+b

ValueError: operands could not be broadcast together with shapes (2,3,1) (2,3) 

In [61]:
a = np.arange(6).reshape(2,3,1)  #(2,3,1) --> (2,3,2)
b = np.arange(6).reshape(3,2)    #(3,2) --> (1,3,2) --> (2,3,2)
a+b

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 3,  4],
        [ 6,  7],
        [ 9, 10]]])

# 인덱싱, 슬라이싱

In [71]:
a = np.arange(12).reshape(3,4)
print(a)

print(a[1])
print(a[2,3])

b = a[0:2, 1:3]
b[0] = 99
print(b)
print(a)    #슬라이싱은 원본의 참조이므로, 원본도 바뀐다. 바꾸지 않으려면 복사를 해야함


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11
[[99 99]
 [ 5  6]]
[[ 0 99 99  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1]
 [5 6]]
[[ 0 99 99  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [90]:
a = np.arange(3,8)
print(a)

print(a[[1,3,4]])    #a의 인덱스를 리스트로 만듦
print(a[a>3])

a = np.arange(30).reshape(5,6)
print(a[[3],[5]])
print(a[[0,2],[2,3]])

b = np.arange(30).reshape(2,5,3)
print(b[[0,1],[2,3],[1,2]])


[3 4 5 6 7]
[4 6 7]
[4 5 6 7]
[23]
[ 2 15]
[ 7 26]


# 병합과 분리

In [98]:
a = np.arange(4).reshape(2,2)
b = np.arange(10,14).reshape(2,2)

print(np.vstack((a,b)))   #수직으로 길어짐
print(np.hstack((a,b)))    #수평으로 길어짐
print() 

c = np.arange(12).reshape(2,2,3)
d = np.arange(10,22).reshape(2,2,3)
print(np.vstack((c,d)))
print(np.hstack((c,d)))
print()

print(np.concatenate((a,b), 0))    #수직으로
print(np.concatenate((a,b), 1))    #수평으로

[[ 0  1]
 [ 2  3]
 [10 11]
 [12 13]]
[[ 0  1 10 11]
 [ 2  3 12 13]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
[[[ 0  1  2]
  [ 3  4  5]
  [10 11 12]
  [13 14 15]]

 [[ 6  7  8]
  [ 9 10 11]
  [16 17 18]
  [19 20 21]]]

[[ 0  1]
 [ 2  3]
 [10 11]
 [12 13]]
[[ 0  1 10 11]
 [ 2  3 12 13]]


In [109]:
a = np.arange(12)
print(np.hsplit(a,3))    #수직으로 분리

b = np.arange(12).reshape(4,3)
print(b)
print(np.vsplit(b,2))    #수평으로 분리

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])